version: "3.8"

services:
  platform:
    build: ./platform
    container_name: ctf-platform
    ports:
      - "8000:8000"
    volumes:
      - ctf-data:/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - SECRET_KEY=9f5bf06bbe7fe94191080e888836c937e408bfa559476832bb0bfe04cb91e16d
      # ── Email whitelist ────────────────────────────────────────────────
      - ALLOWED_EMAILS=chandru@gmail.com,bob@ctfteam.com,charlie@ctfteam.com,diana@ctfteam.com,eve@ctfteam.com,frank@ctfteam.com
      # ── Admin panel password ──────────────────────────────────────────
      - ADMIN_PASSWORD=ctfadmin@2024

  ch47:
    build: ./challenges/ch47-robots
    container_name: ctf-ch47
    ports:
      - "5001:5000"
    restart: unless-stopped

  ch48:
    build: ./challenges/ch48-js
    container_name: ctf-ch48
    ports:
      - "5002:5000"
    restart: unless-stopped

  ch49:
    build: ./challenges/ch49-sqli
    container_name: ctf-ch49
    ports:
      - "5003:5000"
    restart: unless-stopped

  ch50:
    build: ./challenges/ch50-idor
    container_name: ctf-ch50
    ports:
      - "5004:5000"
    restart: unless-stopped

  ch51:
    build: ./challenges/ch51-cmdi
    container_name: ctf-ch51
    ports:
      - "5005:5000"
    restart: unless-stopped

  ch52:
    build: ./challenges/ch52-lfi
    container_name: ctf-ch52
    ports:
      - "5006:5000"
    restart: unless-stopped

  ch53:
    build: ./challenges/ch53-cookie
    container_name: ctf-ch53
    ports:
      - "5007:5000"
    restart: unless-stopped

  ch54:
    build: ./challenges/ch54-jwt
    container_name: ctf-ch54
    ports:
      - "5008:5000"
    restart: unless-stopped

volumes:
  ctf-data:
